### PR TITLE
Add `submissionCalendar` field

### PR DESCRIPTION
**Pull request by volyx**
Field `subissionCalenda`r is necessary for building Leetcode activity chart like this

image

### CODE REVIEW

**Comment by JeremyTsaii** [comment]
Really appreciate the PR! The error handling (to reduce the arguments passed in StatsResponse) is particularly nice. Thanks for also adding tests for the Submission Calendar.

**Comment by JeremyTsaii** [comment]
Just wondering, are you currently planning to build a Leetcode activity chart in a project?

**Comment by volyx** [comment]
@JeremyTsaii Thx! Yes, I was thinking about building an activity chart - https://github.com/JeremyTsaii/leetcode-stats/issues/1

But It may take time because I'm not really good at writing svg and js.

**Comment by JeremyTsaii** [comment]
That's a great idea. That's okay, I look forward to it :).

**Pull request merged**
